### ISSUE TITLE
게시글, 댓글, 대댓글에 작성자 여부 반환이 필요합니다

### ISSUE THREAD

**Issue by yangddoddi** [Dev-illage/Devillage#104]
원래 클라이언트 토큰 값을 이용하려고 했는데 너무 쉽게 조작 가능한 것 같아서 서버에서 판단하는 게 나을 것 같습니다

**Comment by Qone2** [comment]
어떤식으로 조작이 가능할까요?

**Comment by Qone2** [comment]
수정이나 삭제버튼 때문에 그러는거죠? 근데 조작된 토큰으로 수정, 삭제요청을 보내면 서버검증에서 막히지 않을까요?

**Comment by Qone2** [comment]
음 일단 알겠습니다

**Comment by yangddoddi** [comment]
우선 쿠키를 사용하는 것으로 결정했읍니다
