### ISSUE TITLE
게시글 수정 로직이 오작동하고 있는 것 같습니다

### ISSUE THREAD

**Issue by yangddoddi** [Dev-illage/Devillage#110]
서비스계층까지 요청 정보가 올바르게 전송되는 것을 확인했는데
저장되는 것은 태그를 제외하고는 기존 정보 그대로입니다

또한 태그가 계속해서 추가되기만하고 제거할 수 없습니다.

**Comment by gangdodan** [comment]
태그는 어떤 조건으로 삭제되어야 하나요? 별도 요청 api로 처리해야 되는지 내부 로직으로 가능한지 찾아보겠습니다

**Comment by yangddoddi** [comment]
> 태그는 어떤 조건으로 삭제되어야 하나요? 별도 요청 api로 처리해야 되는지 내부 로직으로 가능한지 찾아보겠습니다

제 생각에는 그냥 기존 태그를 다 삭제해버리고 새로 저장하는 게 나을 것 같습니다

**Comment by gangdodan** [comment]
이 이슈도 수정완료, pr은 나머지 이슈와 함께 올리겠습니다.
