### ISSUE TITLE
파일 관련 문제들

### ISSUE THREAD

**Issue by yangddoddi** [Dev-illage/Devillage#140]
![image](https://user-images.githubusercontent.com/97802103/196444672-69605004-4bce-4a89-ac76-ac591bf67447.png)

1. 아바타 객체가 비어있는 상태로 전달되고 있습니다.
2. 댓글, 글 조회에서도 경로가 필요합니다.
3. 그런데 문제는 지금 같은 방식으로는 댓글이 10개 있다면 글 작성자까지 포함해서 글 조회(+댓글 조회) 1회 및 프로필 사진 11번 조회로 총 12번의 api 통신이 필요한데 개선 방안이 없을까요?

**Comment by Qone2** [comment]
일단 avatar가 null인 경우에 avatar내 항목이 전부 null인채로 전달됩니다

**Comment by Qone2** [comment]
댓글 조회시 같이 조회하는걸로 할까요?

**Comment by yangddoddi** [comment]
@Qone2
네 그렇게 변경할 수 있으면 하는 게 좋을 것 같습니다.
그리고 제가 전체 로직은 모르겠지만 일단 해당 유저 id로 db에 이미지가 등록되있으나 Null이 반환되네요..

**Comment by Qone2** [comment]
엇 정말요? User의 avatar_image_id가 null이 아닌데 그렇게 나온다는건가요?

**Comment by yangddoddi** [comment]
@Qone2 
![image](https://user-images.githubusercontent.com/97802103/196459777-460dabe7-72ce-4041-828d-af7fb727881b.png)

넵 디버깅해보니 DTO에서 이미 Null로 잡히고 있습니다
그리고 더 찾아보니 file에는 userId가 저장되어있는데 user에는 avatar_id가 null로 잡히네요

**Comment by Qone2** [comment]
file의 owner_user_id와 user의 avatar_id는 서로 연관이 없는 별개의 컬럼입니다. user의 avatar_id가 null이면 프로필 사진이 등록되어있지 않은것 입니다. file의 owner_user_id는 파일객체의 접근, 수정, 삭제권한 및 검증을 위해 존재합니다.

**Comment by yangddoddi** [comment]
음.. 새로운 api가 생겼군요. 해당 부분은 작동 확인했습니다.
