### ISSUE TITLE
POST /posts (게시글 작성 api) 반환값 수정이 필요합니다

### ISSUE THREAD

**Issue by yangddoddi** [Dev-illage/Devillage#68]
게시글을 작성하면 작성한 게시글을 보여줘야하는데, 반환값으로 게시글 식별자를 보내주지 않아서 해당 로직을 구현할 수 없습니다.
id를 포함해서 반환하도록 변경 부탁드립니다.

**Comment by gangdodan** [comment]
기본적인걸 빠트렸네요. 수정 완료했습니다. pr 완료 후에 이슈 클로즈 하겠습니다~
