### ISSUE TITLE
코멘트 조회 시 서비스 로직 추가 필요

### ISSUE THREAD

**Issue by yangddoddi** [Dev-illage/Devillage#70]
조회한 유저의 토큰 정보를 이용하여 해당 유저가 좋아요를 눌렀는지 boolean으로 반환하는 항목이 추가로 필요합니다.

**Comment by Qone2** [comment]
요청을 따로 만들까요 아니면 같은 api에서 처리할까요?

**Comment by yangddoddi** [comment]
> 요청을 따로 만들까요 아니면 같은 api에서 처리할까요?

같은 api에서 반환 항목만 추가되면 됩니다! 감사합니다.
