### ISSUE TITLE
Get /posts/{id} 문제점 2가지 해결 필요 (좋아요, 수정일 관련)

### ISSUE THREAD

**Issue by yangddoddi** [Dev-illage/Devillage#88]
- [x] 1. 좋아요 true, false 여부가 정상적으로 오지 않고 무조건 false로 반환되고 있습니다 #105
- [ ] 2. 원본인데 modified가 계속 true로 전송되고 있습니다

**Comment by gangdodan** [comment]
2번은 제가 확인해보겠습니다

**Comment by gangdodan** [comment]
(히스토리 기록용)
modify는 게시글 조회할 때 조회수 카운트를 변경 감지해서 true로 나오는 것 같습니다. 
쿼리문으로 해결하려고 했으나 보통 벌크 연산에 사용되는 방식이라 다른 데이터에 문제가 생겨 해당 문제 해결에는 적합하지 않은 방법인 것 같습니다
[](https://stackoverflow.com/questions/63492606/exclude-some-fields-from-audit-with-spring-data-jpa-lastmodifieddate)

그리고 일단 이 문제를 해결한다고 하더라도 post modified 시간이 별도 변경 없이도 second 아래 단위까지 저장되어 근소한 차이로 변경으로 감지되는 상황인 것 같습니다. 이건 원인을 잘 모르겠네요..
e.g)
- 2022-10-06 23:07:49.929720
- 2022-10-06 23:07:49.942851

**Comment by yangddoddi** [comment]
> (히스토리 기록용) modify는 게시글 조회할 때 조회수 카운트를 변경 감지해서 true로 나오는 것 같습니다. 쿼리문으로 해결하려고 했으나 보통 벌크 연산에 사용되는 방식이라 다른 데이터에 문제가 생겨 해당 문제 해결에는 적합하지 않은 방법인 것 같습니다
> 
> 그리고 일단 이 문제를 해결한다고 하더라도 post modified 시간이 별도 변경 없이도 second 아래 단위까지 저장되어 근소한 차이로 변경으로 감지되는 상황인 것 같습니다. 이건 원인을 잘 모르겠네요.. e.g)
> 
> * 2022-10-06 23:07:49.929720
> * 2022-10-06 23:07:49.942851

조회수 카운트 변경되는 걸 생각하지 못했네요.. 패스워드 변경 일자처럼 별도 필드를 만들어서 수정 여부를 체크하지 않는 한 해결책이 없겠습니다.

**Comment by Qone2** [comment]
흠... 그런 이유가 있었네요 따로 isModified 라는 필드를 두어서 관리하면 너무 지저분 할까요?

**Comment by yangddoddi** [comment]
> 흠... 그런 이유가 있었네요 따로 isModified 라는 필드를 두어서 관리하면 너무 지저분 할까요?

그렇게 처리하는 게 오히려 이전보다 깔끔할 것 같네요

**Comment by gangdodan** [comment]
post modified 시간은 디폴트 9999-12-31-00-00 으로 생성하도록 해놨습니다.
다른 이슈와 묶어서 pr 올릴게용
