### ISSUE TITLE
게시글 작성시 태그가 비어있는 경우 발생하는 문제

### ISSUE THREAD

**Issue by Qone2** [Dev-illage/Devillage#95]
```json
{
    "category": "FREE",
    "title": "this is title",
    "content": "this is content"
}
```
이런 요청일때는 nullpointer오류가 나고

```json
{
    "category": "FREE",
    "title": "this is title",
    "tags": [],
    "content": "this is content"
}
```
이런 요청일때는 응답이
```json
{
    "postId": null
}
```
이렇게 나오며 게시글이 저장이 안됩니다.

**Comment by gangdodan** [comment]
null로 저장되는 방법을 계속 찾고 있는데 잘 안되네요. 이메일 인증 테스트 완료하구 다시 체크해보겠습니다~~~

**Comment by yangddoddi** [comment]
> null로 저장되는 방법을 계속 찾고 있는데 잘 안되네요. 이메일 인증 테스트 완료하구 다시 체크해보겠습니다~~~

이부분 아직 해결이 잘 안되고 있는 건가요?

**Comment by gangdodan** [comment]
네 후순위로 두고 보니 많이 밀렸는데 오늘 저녁 안으로 해결해서 pr 올리겠습니다
