### ISSUE TITLE
각자 맡은 파트에서 DTO Validation을 설정해주세요(수정)

### ISSUE THREAD

**Issue by yangddoddi** [Dev-illage/Devillage#99]
validation이 적절하게 설정되지 않아 500 에러가 나오는 경우가 너무 많습니다.

게시글, 댓글 관련 : 특이사항 있는 경우가 아니라면 대부분 NotBlnak가 들어가야 합니다.
Email, Nickname, Password등 유저 관련 : 정책은 AuthDto를 참고해서 설정해주세요, 마찬가지로 특이사항 없으면 NotBlank가 기본으로 포함되어야 합니다.

**Comment by Qone2** [comment]
NotBlank는 어떤가요

**Comment by yangddoddi** [comment]
> NotBlank는 어떤가요

제가 착각했네요 NotBlank로 해야하는 게 맞습니다!
